"""raw_orders_direct

Revision ID: 0013
Revises: 0012
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from warehouse.migrations.helpers import (  # noqa: F401
    JSONB,
    LINE_QTY,
    MONEY,
    NOW,
    QTY,
    RATING,
    RATIO,
    TEXT,
    TEXT_ARRAY,
    TIMESTAMPTZ,
    UNIT_MONEY,
    UUID,
    YIELD,
    ck,
    create_extension_if_absent,
    create_index_if_absent,
    create_table_if_absent,
    created_at_column,
    drop_index_if_present,
    drop_table_if_present,
    excl,
    fk,
    pk_column,
    pk_constraint,
    replace_constraint,
    slug_column,
    updated_at_column,
    uq,
)

revision: str = "0013"
down_revision: str | Sequence[str] | None = "0012"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

TABLE = "raw_orders_direct"


def upgrade() -> None:
    # RAW LANDING per ARCHITECTURE.md section 4.1: "land raw into a raw_* table
    # first, transform second." One table PER SOURCE, not a generalized
    # raw_orders(source, ...): a polymorphic table's schema would have to
    # compromise across sources that don't actually look alike (a D1 SQLite row
    # vs. a future Lieferando webhook body), and its own UNIQUE arbiter would
    # need (source, external_id) anyway - no savings. Revisit only if a 4th/5th
    # order-shaped source makes the duplication genuinely painful.
    #
    # No `channel` column: unlike `orders`, this table only ever holds
    # 'direct' rows by construction - a CHECK-constrained single value here
    # would be ceremony, not a safety net.
    create_table_if_absent(
        TABLE,
        pk_column(),
        pk_constraint(TABLE),
        # The D1 orders.id ('ord_<uuid>'), server-generated by the ordering
        # backend. Same value orders.external_id gets after transform, so a raw
        # row and its transformed row are traceable by eye.
        sa.Column("external_id", TEXT, nullable=False),
        # Verbatim order, items nested as payload['items']: [{sku,
        # unit_price_cents, quantity}, ...]. Deliberately UNTRANSFORMED - cents
        # stay cents, timestamps stay ISO-8601 strings - so the transform can be
        # re-derived without re-hitting D1 if its mapping logic is ever wrong.
        sa.Column("payload", JSONB, nullable=False),
        created_at_column(),  # first extraction run that landed this row
        updated_at_column(),  # most recent extraction run that re-confirmed it
        sa.UniqueConstraint("external_id", name=uq(TABLE, "external_id")),
    )


def downgrade() -> None:
    drop_table_if_present(TABLE)
